'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TABLE If NOT EXISTS FMFiles (Ver varchar(255), Filename varchar(255), File"& _ 
            "Size INT, MissionName varchar(255), Author varchar(255), ReleaseDate DATE, Ratin"& _ 
            "g INT, Completed varchar(255), FileTypes varchar(255), Directory varchar(255), I"& _ 
            "nstallFolder varchar(255), Hash varchar(255))")>  _
        Public ReadOnly Property CreateTableFMFiles() As String
            Get
                Return CType(Me("CreateTableFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TABLE IF NOT EXISTS InfoFiles (FMFilesId INT, Filename varchar(255), Conte"& _ 
            "nt BLOB)")>  _
        Public ReadOnly Property CreateTableInfoFiles() As String
            Get
                Return CType(Me("CreateTableInfoFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TRIGGER IF NOT EXISTS FMDelete AFTER DELETE ON FMFiles FOR EACH ROW BEGIN "& _ 
            "DELETE FROM InfoFiles WHERE FMFilesId = OLD.rowid; END")>  _
        Public ReadOnly Property CreateTriggerFMDelete() As String
            Get
                Return CType(Me("CreateTriggerFMDelete"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO FMFiles (Ver, Filename, FileSize, MissionName, Author, ReleaseDate, R"& _ 
            "ating, Completed, FileTypes, Directory, InstallFolder, Hash) VALUES ('{0}','{1}'"& _ 
            ",'{2}','{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}')")>  _
        Public ReadOnly Property InsertMissionFile() As String
            Get
                Return CType(Me("InsertMissionFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM FMFiles WHERE Directory = '{0}' AND Filename = '{1}'")>  _
        Public ReadOnly Property DeleteMissionFile() As String
            Get
                Return CType(Me("DeleteMissionFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT rowid, Ver, Filename, FileSize, MissionName, Author, ReleaseDate, Rating, "& _ 
            "Completed, FileTypes, Directory, InstallFolder, Hash FROM FMFiles")>  _
        Public ReadOnly Property SelectAllFMFiles() As String
            Get
                Return CType(Me("SelectAllFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE FMFiles SET Ver = '{0}', MissionName = '{1}', Author = '{2}', ReleaseDate "& _ 
            "= '{3}', Rating = {4}, Completed = '{5}' WHERE rowid = {6}")>  _
        Public ReadOnly Property UpdateFMFiles() As String
            Get
                Return CType(Me("UpdateFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Filename, Hash FROM FMFiles")>  _
        Public ReadOnly Property SelectFileHash() As String
            Get
                Return CType(Me("SelectFileHash"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO InfoFiles VALUES ('{0}', '{1}', @bytes)")>  _
        Public ReadOnly Property InsertInfoFile() As String
            Get
                Return CType(Me("InsertInfoFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Filename, Content FROM InfoFiles WHERE FMFilesId = {0}")>  _
        Public ReadOnly Property SelectInfoFiles() As String
            Get
                Return CType(Me("SelectInfoFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT rowid, Ver, Filename, FileSize, MissionName, Author, ReleaseDate, Rating, "& _ 
            "Completed, FileTypes, Directory, InstallFolder, Hash FROM FMFiles WHERE Ver = '{"& _ 
            "0}'")>  _
        Public ReadOnly Property SelectGameFMFiles() As String
            Get
                Return CType(Me("SelectGameFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TABLE IF NOT EXISTS UserNotes (FMFilesId INT NOT NULL PRIMARY KEY, Note TE"& _ 
            "XT)")>  _
        Public ReadOnly Property CreateTableUserNotes() As String
            Get
                Return CType(Me("CreateTableUserNotes"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Note FROM UserNotes WHERE FMFilesId = {0}")>  _
        Public ReadOnly Property SelectUserNotes() As String
            Get
                Return CType(Me("SelectUserNotes"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT OR REPLACE INTO UserNotes VALUES ({0}, '{1}')")>  _
        Public ReadOnly Property UpdateUserNote() As String
            Get
                Return CType(Me("UpdateUserNote"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TIPS:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1. Edit MissionName, Author, ReleaseDate by clicking in the cell and sta"& _ 
            "rt typing, or click 2-3 times for it to enter edit mode. Changes are saved as yo"& _ 
            "u click out of the row."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2. Copy metadata from one mission to another by draggin"& _ 
            "g the source row to the target row."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3. If the detected mission type (Ver column"& _ 
            ") is incorrect, double-click to change it."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"4. Click on the stars in the Rating "& _ 
            "column to set your rating for each mission. Click the very left edge of the firs"& _ 
            "t star to set it to zero."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5. Use the Completed column to keep track what what m"& _ 
            "issions you've completed and what difficulty you completed. Choose yes if the mi"& _ 
            "ssion does not have difficulty levels."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"6. Use the User Notes tab for each missi"& _ 
            "on to keep notes about that mission."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"7. Type in the Filter textbox to search by"& _ 
            " FileName, MissionName, and Author. Clear the textbox to show all missions."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"8. "& _ 
            "Click the Sync button after missions have been added or deleted from your archiv"& _ 
            "e folder to update the mission list."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"9. The Max Cash checkbox (for T1 & T2) giv"& _ 
            "es you the maximum cash available to use for loadouts."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"10. Click the down-arrow"& _ 
            " next to the Play Fan Mission button to play the original missions."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"11. Double-"& _ 
            "clicking in a file or folder column will open the file or folder with the defaul"& _ 
            "t program."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"12. Closing the program by using the Exit menu item or closing the m"& _ 
            "ain window will exit without launching the game."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"13. Use the donation links to "& _ 
            "support development if you like the launcher.")>  _
        Public ReadOnly Property AboutText() As String
            Get
                Return CType(Me("AboutText"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>0 - (Default)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1 - Lord Bafford's Manor</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
            "ring>2 - Break from Cragscleft Prison</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>3 - Down in the Boneho"& _ 
            "ard</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>4 - Assassins</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>5 - Thieves Guild</str"& _ 
            "ing>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>6 - The Sword</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>7 - The Haunted Cathedral</str"& _ 
            "ing>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>8 - The Mage Towers</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>9 - The Lost City</strin"& _ 
            "g>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>10 - Song of the Caverns</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>11 - Undercover</stri"& _ 
            "ng>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>12 - Return to the Cathedral</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>13 - Escape!</st"& _ 
            "ring>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>14 - Strange Bedfellows</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>15 - Into the Maw o"& _ 
            "f Chaos</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>16 - Blooper Reel</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public ReadOnly Property T1OrigMissions() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("T1OrigMissions"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>0 - (Default)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1 - Running Interference</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
            "ring>2 - Shipping ... and Receiving</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>3 - Framed</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
            "string>4 - Ambush!</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>5 - Eavesdropping</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>6 -"& _ 
            " First City Bank and Trust</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>7 - Blackmail</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string"& _ 
            ">8 - Trace the Courier</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>9 - Trail of Blood</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <strin"& _ 
            "g>10 - Life of the Party</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>11 - Precious Cargo</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
            "ring>12 - Kidnap</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>13 - Casing the Joint</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1"& _ 
            "4 - Masks</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>15 - Sabotage at Soulforge</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfStri"& _ 
            "ng>")>  _
        Public ReadOnly Property T2OrigMissions() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("T2OrigMissions"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<html>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<head><style>.GLTITLE {font-size: 18pt;font-weight: bold;color: 000000;te"& _ 
            "xt-decoration: none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLSUBTITLE {font-size: 14pt;fo"& _ 
            "nt-weight: bold;color: 000000;text-decoration: none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLAUTHOR {font-size:  10pt;font-weight: bold;color: 000000;text-decoration: no"& _ 
            "ne;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLFMINFO {font-size:  10pt;font-weight: bold;co"& _ 
            "lor: 000000;text-decoration: none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLBRIEFING {font"& _ 
            "-size:  10pt;font-weight: bold;color: 000000;text-decoration: none;font-family: "& _ 
            "MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLFMSTRUCTURE {font-size:  10pt;font-weight: bold;color: 000000"& _ 
            ";text-decoration: none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLWARNINGS {font-size:  12p"& _ 
            "t;font-weight: bold; color:FF0000; text-decoration:none;font-family: MS Sans Ser"& _ 
            "if}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLBUILD {font-size:  10pt;font-weight: bold;color: 000000;text-decoration:"& _ 
            " none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLINFO {font-size:  10pt;font-weight: bold;c"& _ 
            "olor: 000000;text-decoration: none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLLOADING {font"& _ 
            "-size:  10pt;font-weight: bold;color: 000000;text-decoration: none;font-family: "& _ 
            "MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".GLCOPYRIGHT{font-size:  10pt;font-weight: bold;color: 000000;te"& _ 
            "xt-decoration: none;font-family: MS Sans Serif}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".INTELLITEXT{border-bottom 1 do"& _ 
            "uble red}.TEXTRED{color: Red;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTDARKRED{color: DarkRed;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTVIOLETRED{co"& _ 
            "lor: VioletRed ;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTDARKMAGENTA{color: DarkMagenta ;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTWHITE{color: whi"& _ 
            "te;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTBLUE{color: Blue;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTDARKBLUE{color: DarkBlue ;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTLIME{color"& _ 
            ": Lime;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTBLACK{color: Black;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTYELLOW{color: Yellow;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTGREEN{col"& _ 
            "or: Green;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".TEXTGRAY{color: Gray;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTYELLOW{background-color: yellow;"& _ 
            "}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTLIGHTYELLOW{background-color: #FFFFCC;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTCREAM{background"& _ 
            "-color: LemonChiffon;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTLIGHTOLDLACE{background-color: Oldlace;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIG"& _ 
            "HLIGHTLIME{background-color: lime;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTHONEYDEW{background-color: HoneyD"& _ 
            "ew;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTRED{background-color: red;color:white;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTPINK{backgrou"& _ 
            "nd-color: pink;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTTHISTLE{background-color: thistle;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTORANG"& _ 
            "E{background-color:orange;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTAQUA{background-color:aqua;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&".HIGHLIGHTW"& _ 
            "HITE{background-color:white;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"body {scrollbar-arrow-color:#000000;scrollbar-dar"& _ 
            "kshadow-color:#000000;}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</style>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<meta http-equiv='Content-Type' content='text"& _ 
            "/html; charset=UTF-8' />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</head>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<body bgcolor='#FFFFFF' ><div style='position"& _ 
            ":absolute;top:15px;left:3px;'>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"<center><span class=""GLTITLE"">Guidance on scori"& _ 
            "ng FMs</span></center>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"<br><br><span class=""GLFMINFO"">It is often difficult to"& _ 
            " actually score and FM once you have played it.<br>Below we will go through a fe"& _ 
            "w pro's and con's of the best way to score and FM (mainly based on the Thief FMs"& _ 
            " but this would also apply to other games as well) and an chart that will help y"& _ 
            "ou to get a good idea of what you should score an FM on."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<br><br>Here are a f"& _ 
            "ew tips on how best to score FMs."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<ol>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""HIGHLIGHTHONEYDEW TEXTB"& _ 
            "LACK"">DO: Start with the concept that the original missions are at a score of 8 "& _ 
            "or 9, then based on them compare the FMs to that. I.E. if a mission exceeds the "& _ 
            "original missions then give it 8,9 or 10 based upon your view of how much better"& _ 
            " the FM is.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""HIGHLIGHTHONEYDEW TEXTBLACK"">DO: Consider limita"& _ 
            "tions of the editor or game engine, if there are difficulties or restrictions as"& _ 
            " to how the FM can run due to the engine don't let it affect your judgement. I.E"& _ 
            ". Thief Deadly Shadows is a different engine to Thief 1 and 2 so don't compare t"& _ 
            "hem against each other, you are judging the work put into the FM.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li c"& _ 
            "lass=""HIGHLIGHTHONEYDEW TEXTBLACK"">DO: Score only when you have completed the FM"& _ 
            ", preferably on a couple of different difficulty levels. If you could not comple"& _ 
            "te because of a fault in the FM consider it unscorable until a fixed version is "& _ 
            "released.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""HIGHLIGHTHONEYDEW TEXTBLACK"">DO: Try an avoid the "& _ 
            "human reaction of giving everything a high average score.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""HI"& _ 
            "GHLIGHTHONEYDEW TEXTBLACK"">DO: Be forgiving, no fan mission will be 100% perfect"& _ 
            ", lower your standards slightly to compensate that and score accordingly. Also b"& _ 
            "e forgiving, if you stumble apon a slightly sticky bit of floor, or a small bit "& _ 
            "of untextured area in a large mission, DO NOT score lower because of it, everyon"& _ 
            "e makes mistakes.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""HIGHLIGHTHONEYDEW TEXTBLACK"">DO: Score onl"& _ 
            "y on areas you are supposed to go in the mission, if you find that you have mana"& _ 
            "ged to scale a building and are seeing bits that look like you should not be see"& _ 
            "ing (as they are dull, missing textures, etc, don't consider those areas in your"& _ 
            " final score.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""HIGHLIGHTPINK TEXTBLACK"">DO NOT: Score the FM "& _ 
            "based upon the game engine. E.G. if you did not like the way Garrett moves in Th"& _ 
            "ief Deadly Shadows, do not score the FM low because of that as you will only be "& _ 
            "scoreing the original game and not the custom work put in.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li class=""H"& _ 
            "IGHLIGHTPINK TEXTBLACK"">DO NOT: Score the FM based upon if it frustrated you or "& _ 
            "was not your kind of FM. I.E. if it had lots of undead in it and you don't like "& _ 
            "undead, don't give it a 1 because of that, be fair and score based upon how well"& _ 
            " it played, use of content, storyline, etc.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"</ol>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<br>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"Effectively"& _ 
            " the best way to score is by using the scales below to give an overall result:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<center>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<script language=""JavaScript"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"function Calculate_score()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(9)&"{"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"var myscore = 0;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = myscore+parseInt(document.all.story.valu"& _ 
            "e);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = myscore+parseInt(document.all.Architecture.value);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"mysco"& _ 
            "re = myscore+parseInt(document.all.Playablity.value);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = myscore+par"& _ 
            "seInt(document.all.Enjoyment.value);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = myscore+parseInt(document.al"& _ 
            "l.Innovation.value);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = myscore+parseInt(document.all.Custom.value);"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = myscore+parseInt(document.all.mySize.value);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = mysc"& _ 
            "ore+parseInt(document.all.myTheme.value);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"myscore = Math.round((myscore / 8"& _ 
            "0)*10);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"if (myscore < 4)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"{"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalvalue.style.backgr"& _ 
            "oundColor='red';"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalvalue.style.color='white';"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(9)&"else if (myscore < 8)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"{"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalvalue.style.backgroundCol"& _ 
            "or='LemonChiffon';"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalvalue.style.color='black';"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"else"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"{"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalvalue.style.backgroundColor='lime';"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalvalue.style.color='black';"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"document.all.totalva"& _ 
            "lue.innerText = myscore;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"</script>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<table border=""1"" width=""95%"" ce"& _ 
            "llspacing=""0"" cellpadding=""0"" class=""GLFMINFO"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr class=""HIGHLIGHTTHISTLE "& _ 
            "TEXTBLACK"" align=""center""><td style=""border-style:outset;"">Scale</td><td style="""& _ 
            "border-style:outset;"">High (Score 8-10)</td><td style=""border-style:outset;"">Ave"& _ 
            "rage (Score 4-7)</td><td style=""border-style:outset;"">Low (Score 1-3)</td><td st"& _ 
            "yle=""border-style:outset;"">Your Score</td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTHIS"& _ 
            "TLE TEXTBLACK"" style=""border-style:outset;"" align=""right"">Story</td><td class=""H"& _ 
            "IGHLIGHTHONEYDEW TEXTBLACK"">You were drawn into the story as the FM progressed</"& _ 
            "td><td class=""HIGHLIGHTLIGHTYELLOW TEXTBLACK"">It was interesting but the story w"& _ 
            "as just background to the events on screen and wasn't really that gripping</td><"& _ 
            "td class=""HIGHLIGHTPINK TEXTBLACK"">You had no idea what was going on (this does "& _ 
            "not count for foreign language FMs)</td><td style=""border-style:outset;""><select"& _ 
            " name=""story"" onChange=""Calculate_score();""><option value=""10"">10</option><optio"& _ 
            "n value=""9"">9</option><option value=""8"">8</option><option value=""7"">7</option><o"& _ 
            "ption value=""6"">6</option><option value=""5"">5</option><option value=""4"">4</optio"& _ 
            "n><option value=""3"">3</option><option value=""2"">2</option><option value=""1"">1</o"& _ 
            "ption></select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTHISTLE TEXTBLACK"" style="""& _ 
            "border-style:outset;"" align=""right"">Architecture</td><td class=""HIGHLIGHTHONEYDE"& _ 
            "W TEXTBLACK"">The scenery was stunning, there were few or no big, same texture, b"& _ 
            "lank or dull areas of wall or floor.</td><td class=""HIGHLIGHTLIGHTYELLOW TEXTBLA"& _ 
            "CK"">There were some good designed buildings or scenery, however there was also s"& _ 
            "ome big areas of blank almost unfinished sections.</td><td class=""HIGHLIGHTPINK "& _ 
            "TEXTBLACK"">Everything looked the same, it was very square and lacked any kind of"& _ 
            " detail.</td><td style=""border-style:outset;""><select name=""Architecture"" onChan"& _ 
            "ge=""Calculate_score();""><option value=""10"">10</option><option value=""9"">9</optio"& _ 
            "n><option value=""8"">8</option><option value=""7"">7</option><option value=""6"">6</o"& _ 
            "ption><option value=""5"">5</option><option value=""4"">4</option><option value=""3"">"& _ 
            "3</option><option value=""2"">2</option><option value=""1"">1</option></select></td>"& _ 
            "</tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTHISTLE TEXTBLACK"" style=""border-style:outset;"& _ 
            """ align=""right"">Playablity</td><td class=""HIGHLIGHTHONEYDEW TEXTBLACK"">You could"& _ 
            " do everything you expected to be able to do, puzzles were challenging but not i"& _ 
            "mpossible and tasks were not a chore.</td><td class=""HIGHLIGHTLIGHTYELLOW TEXTBL"& _ 
            "ACK"">You had trouble with some tasks not working properly or puzzles being too d"& _ 
            "ifficult.</td><td class=""HIGHLIGHTPINK TEXTBLACK"">A puzzle solution made no sens"& _ 
            "e or didn't work at all. Tasks felt repetative, too long winded or were very dul"& _ 
            "l.</td><td style=""border-style:outset;""><select name=""Playablity"" onChange=""Calc"& _ 
            "ulate_score();""><option value=""10"">10</option><option value=""9"">9</option><optio"& _ 
            "n value=""8"">8</option><option value=""7"">7</option><option value=""6"">6</option><o"& _ 
            "ption value=""5"">5</option><option value=""4"">4</option><option value=""3"">3</optio"& _ 
            "n><option value=""2"">2</option><option value=""1"">1</option></select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTHISTLE TEXTBLACK"" style=""border-style:outset;"" align="& _ 
            """right"">Enjoyment</td><td class=""HIGHLIGHTHONEYDEW TEXTBLACK"">You have played it"& _ 
            " once through and want to play it again and again. It was great fun to play and "& _ 
            "you were dissapointed when it ended.</td><td class=""HIGHLIGHTLIGHTYELLOW TEXTBLA"& _ 
            "CK"">It was enjoyable, but you couldn't help but feel it was missing something.</"& _ 
            "td><td class=""HIGHLIGHTPINK TEXTBLACK"">You couldn't wait for the mission to end,"& _ 
            " it was dull, really frustrating and not worth playing.</td><td style=""border-st"& _ 
            "yle:outset;""><select name=""Enjoyment"" onChange=""Calculate_score();""><option valu"& _ 
            "e=""10"">10</option><option value=""9"">9</option><option value=""8"">8</option><optio"& _ 
            "n value=""7"">7</option><option value=""6"">6</option><option value=""5"">5</option><o"& _ 
            "ption value=""4"">4</option><option value=""3"">3</option><option value=""2"">2</optio"& _ 
            "n><option value=""1"">1</option></select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTH"& _ 
            "ISTLE TEXTBLACK"" style=""border-style:outset;"" align=""right"">Innovation</td><td c"& _ 
            "lass=""HIGHLIGHTHONEYDEW TEXTBLACK"">The FM broke new ground, there were things ne"& _ 
            "ver tried before which worked really well.</td><td class=""HIGHLIGHTLIGHTYELLOW T"& _ 
            "EXTBLACK"">There were things not often used or cleverly put together but they may"& _ 
            " not have been used to their best effect.</td><td class=""HIGHLIGHTPINK TEXTBLACK"& _ 
            """>There was nothing new in the FM, it lacked a lot of basic standards (switches,"& _ 
            " secrets, scripting, all where applicable).</td><td style=""border-style:outset;"""& _ 
            "><select name=""Innovation"" onChange=""Calculate_score();""><option value=""10"">10</"& _ 
            "option><option value=""9"">9</option><option value=""8"">8</option><option value=""7"""& _ 
            ">7</option><option value=""6"">6</option><option value=""5"">5</option><option value"& _ 
            "=""4"">4</option><option value=""3"">3</option><option value=""2"">2</option><option v"& _ 
            "alue=""1"">1</option></select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTHISTLE TEXTB"& _ 
            "LACK"" style=""border-style:outset;"" align=""right"">Custom Content</td><td class=""H"& _ 
            "IGHLIGHTHONEYDEW TEXTBLACK"">It was packed full of new objects, textures, creatur"& _ 
            "es, and gameplay.</td><td class=""HIGHLIGHTLIGHTYELLOW TEXTBLACK"">It had some new"& _ 
            " objects but they may not have been suitable, or it had some new textures which "& _ 
            "may not have been best suited.</td><td class=""HIGHLIGHTPINK TEXTBLACK"">There was"& _ 
            " nothing new in the FM, and what default content was used may have been used bad"& _ 
            "ly.</td><td style=""border-style:outset;""><select name=""Custom"" onChange=""Calcula"& _ 
            "te_score();""><option value=""10"">10</option><option value=""9"">9</option><option v"& _ 
            "alue=""8"">8</option><option value=""7"">7</option><option value=""6"">6</option><opti"& _ 
            "on value=""5"">5</option><option value=""4"">4</option><option value=""3"">3</option><"& _ 
            "option value=""2"">2</option><option value=""1"">1</option></select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<"& _ 
            "tr><td class=""HIGHLIGHTTHISTLE TEXTBLACK"" style=""border-style:outset;"" align=""ri"& _ 
            "ght"">Size</td><td class=""HIGHLIGHTHONEYDEW TEXTBLACK"">The FM was big, or felt bi"& _ 
            "g but was also unique around each corner (i.e. it wasn't repeated over and over,"& _ 
            " unless the story called for that).</td><td class=""HIGHLIGHTLIGHTYELLOW TEXTBLAC"& _ 
            "K"">It was fairly large in size, but you felt it could have been bigger.</td><td "& _ 
            "class=""HIGHLIGHTPINK TEXTBLACK"">You completed it in under 5 minutes without chea"& _ 
            "ting, it is not really re-playable.</td><td style=""border-style:outset;""><select"& _ 
            " name=""mySize"" onChange=""Calculate_score();""><option value=""10"">10</option><opti"& _ 
            "on value=""9"">9</option><option value=""8"">8</option><option value=""7"">7</option><"& _ 
            "option value=""6"">6</option><option value=""5"">5</option><option value=""4"">4</opti"& _ 
            "on><option value=""3"">3</option><option value=""2"">2</option><option value=""1"">1</"& _ 
            "option></select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr><td class=""HIGHLIGHTTHISTLE TEXTBLACK"" style="& _ 
            """border-style:outset;"" align=""right"">Theme / Setting</td><td class=""HIGHLIGHTHON"& _ 
            "EYDEW TEXTBLACK"">The theme of the FM suited the story, the sets made sense and w"& _ 
            "ere suitable. There was also the right balance of AI and puzzles.</td><td class="& _ 
            """HIGHLIGHTLIGHTYELLOW TEXTBLACK"">Sets were ok, but some things did not and were "& _ 
            "not part of the story (for example: a zombie freely walking round a mansion full"& _ 
            " of guards).</td><td class=""HIGHLIGHTPINK TEXTBLACK"">The theme was overdone, the"& _ 
            " settings made no sense to the story (for example: there were too many zombies/g"& _ 
            "uards for the mission, or you suddenly found yourself on a boat with no explanat"& _ 
            "ion of how you got there).</td><td style=""border-style:outset;""><select name=""my"& _ 
            "Theme"" onChange=""Calculate_score();""><option value=""10"">10</option><option value"& _ 
            "=""9"">9</option><option value=""8"">8</option><option value=""7"">7</option><option v"& _ 
            "alue=""6"">6</option><option value=""5"">5</option><option value=""4"">4</option><opti"& _ 
            "on value=""3"">3</option><option value=""2"">2</option><option value=""1"">1</option><"& _ 
            "/select></td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<tr class=""HIGHLIGHTTHISTLE TEXTBLACK""><td style=""border-"& _ 
            "style:outset;"" colspan=""4""><BIG>Total</BIG></td><td id=""totalvalue"" style=""borde"& _ 
            "r-style:outset;"" align=""center"">10</td></tr>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"</table>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<br>Above all rememb"& _ 
            "er that people are making these FMs for you for free, normally a lot of love and"& _ 
            " hard work go into them. So if you do think a Fan Mission is lacking somewhat, l"& _ 
            "et the author know and give them some constructive suggestions on how to improve"& _ 
            " them."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"</span>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</body></html>")>  _
        Public ReadOnly Property GLScoringGuidelines() As String
            Get
                Return CType(Me("GLScoringGuidelines"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TFMM.My.MySettings
            Get
                Return Global.TFMM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
