'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TABLE If NOT EXISTS FMFiles (Ver varchar(255), Filename varchar(255), File"& _ 
            "Size INT, MissionName varchar(255), Author varchar(255), ReleaseDate DATE, Ratin"& _ 
            "g INT, Completed varchar(255), FileTypes varchar(255), Directory varchar(255), I"& _ 
            "nstallFolder varchar(255), Hash varchar(255))")>  _
        Public ReadOnly Property CreateTableFMFiles() As String
            Get
                Return CType(Me("CreateTableFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TABLE IF NOT EXISTS InfoFiles (FMFilesId INT, Filename varchar(255), Conte"& _ 
            "nt BLOB)")>  _
        Public ReadOnly Property CreateTableInfoFiles() As String
            Get
                Return CType(Me("CreateTableInfoFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TRIGGER IF NOT EXISTS FMDelete AFTER DELETE ON FMFiles FOR EACH ROW BEGIN "& _ 
            "DELETE FROM InfoFiles WHERE FMFilesId = OLD.rowid; END")>  _
        Public ReadOnly Property CreateTriggerFMDelete() As String
            Get
                Return CType(Me("CreateTriggerFMDelete"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO FMFiles (Ver, Filename, FileSize, MissionName, Author, ReleaseDate, R"& _ 
            "ating, Completed, FileTypes, Directory, InstallFolder, Hash) VALUES ('{0}','{1}'"& _ 
            ",'{2}','{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}')")>  _
        Public ReadOnly Property InsertMissionFile() As String
            Get
                Return CType(Me("InsertMissionFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM FMFiles WHERE Directory = '{0}' AND Filename = '{1}'")>  _
        Public ReadOnly Property DeleteMissionFile() As String
            Get
                Return CType(Me("DeleteMissionFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT rowid, Ver, Filename, FileSize, MissionName, Author, ReleaseDate, Rating, "& _ 
            "Completed, FileTypes, Directory, InstallFolder, Hash FROM FMFiles")>  _
        Public ReadOnly Property SelectAllFMFiles() As String
            Get
                Return CType(Me("SelectAllFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE FMFiles SET Ver = '{0}', MissionName = '{1}', Author = '{2}', ReleaseDate "& _ 
            "= '{3}', Rating = {4}, Completed = '{5}' WHERE rowid = {6}")>  _
        Public ReadOnly Property UpdateFMFiles() As String
            Get
                Return CType(Me("UpdateFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Filename, Hash FROM FMFiles")>  _
        Public ReadOnly Property SelectFileHash() As String
            Get
                Return CType(Me("SelectFileHash"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO InfoFiles VALUES ('{0}', '{1}', @bytes)")>  _
        Public ReadOnly Property InsertInfoFile() As String
            Get
                Return CType(Me("InsertInfoFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Filename, Content FROM InfoFiles WHERE FMFilesId = {0}")>  _
        Public ReadOnly Property SelectInfoFiles() As String
            Get
                Return CType(Me("SelectInfoFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT rowid, Ver, Filename, FileSize, MissionName, Author, ReleaseDate, Rating, "& _ 
            "Completed, FileTypes, Directory, InstallFolder, Hash FROM FMFiles WHERE Ver = '{"& _ 
            "0}'")>  _
        Public ReadOnly Property SelectGameFMFiles() As String
            Get
                Return CType(Me("SelectGameFMFiles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CREATE TABLE IF NOT EXISTS UserNotes (FMFilesId INT NOT NULL PRIMARY KEY, Note TE"& _ 
            "XT)")>  _
        Public ReadOnly Property CreateTableUserNotes() As String
            Get
                Return CType(Me("CreateTableUserNotes"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Note FROM UserNotes WHERE FMFilesId = {0}")>  _
        Public ReadOnly Property SelectUserNotes() As String
            Get
                Return CType(Me("SelectUserNotes"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT OR REPLACE INTO UserNotes VALUES ({0}, '{1}')")>  _
        Public ReadOnly Property UpdateUserNote() As String
            Get
                Return CType(Me("UpdateUserNote"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TIPS:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1. Edit MissionName, Author, ReleaseDate by clicking in the cell and sta"& _ 
            "rt typing, or click 2-3 times for it to enter edit mode. Changes are saved as yo"& _ 
            "u click out of the row."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2. Copy metadata from one mission to another by draggin"& _ 
            "g the source row to the target row."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3. If the detected mission type (Ver column"& _ 
            ") is incorrect, double-click to change it."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"4. Click on the stars in the Rating "& _ 
            "column to set your rating for each mission. Click the very left edge of the firs"& _ 
            "t star to set it to zero."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5. Use the Completed column to keep track what what m"& _ 
            "issions you've completed and what difficulty you completed. Choose yes if the mi"& _ 
            "ssion does not have difficulty levels."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"6. Use the User Notes tab for each missi"& _ 
            "on to keep notes about that mission."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"7. Type in the Filter textbox to search by"& _ 
            " FileName, MissionName, and Author. Clear the textbox to show all missions."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"8. "& _ 
            "Click the Sync button after missions have been added or deleted from your archiv"& _ 
            "e folder to update the mission list."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"9. The Max Cash checkbox (for T1 & T2) giv"& _ 
            "es you the maximum cash available to use for loadouts."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"10. Click the down-arrow"& _ 
            " next to the Play Fan Mission button to play the original missions."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"11. Double-"& _ 
            "clicking in a file or folder column will open the file or folder with the defaul"& _ 
            "t program."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"12. Closing the program by using the Exit menu item or closing the m"& _ 
            "ain window will exit without launching the game."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"13. Use the donation links to "& _ 
            "support development if you like the launcher.")>  _
        Public ReadOnly Property AboutText() As String
            Get
                Return CType(Me("AboutText"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>0 - (Default)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1 - Lord Bafford's Manor</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
            "ring>2 - Break from Cragscleft Prison</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>3 - Down in the Boneho"& _ 
            "ard</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>4 - Assassins</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>5 - Thieves Guild</str"& _ 
            "ing>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>6 - The Sword</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>7 - The Haunted Cathedral</str"& _ 
            "ing>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>8 - The Mage Towers</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>9 - The Lost City</strin"& _ 
            "g>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>10 - Song of the Caverns</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>11 - Undercover</stri"& _ 
            "ng>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>12 - Return to the Cathedral</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>13 - Escape!</st"& _ 
            "ring>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>14 - Strange Bedfellows</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>15 - Into the Maw o"& _ 
            "f Chaos</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>16 - Blooper Reel</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public ReadOnly Property T1OrigMissions() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("T1OrigMissions"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>0 - (Default)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1 - Running Interference</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
            "ring>2 - Shipping ... and Receiving</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>3 - Framed</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
            "string>4 - Ambush!</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>5 - Eavesdropping</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>6 -"& _ 
            " First City Bank and Trust</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>7 - Blackmail</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string"& _ 
            ">8 - Trace the Courier</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>9 - Trail of Blood</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <strin"& _ 
            "g>10 - Life of the Party</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>11 - Precious Cargo</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
            "ring>12 - Kidnap</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>13 - Casing the Joint</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1"& _ 
            "4 - Masks</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>15 - Sabotage at Soulforge</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfStri"& _ 
            "ng>")>  _
        Public ReadOnly Property T2OrigMissions() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("T2OrigMissions"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TFMM.My.MySettings
            Get
                Return Global.TFMM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
